server:
  servlet:
    context-path: /foodemo

  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/foodemo
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 20
  servlet:
    multipart:
      max-file-size: 3MB
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      static-locations[0]: file:src/main/resources/static
      static-locations[1]: classpath:/static/